const options = [
    "PCPE - DIM - 3ª Delegacia Seccional de Policia - Boa Viagem (PCPE - DIM - 3ª DESEC)",
"Arquivo Criminal do IITB (PCPE - IITB - ARCRIM)",
"Assessoria - DRACCO (PCPE - DRACCO - ASSDRACCO)",
"Assessoria do Gabinete - IITB (PCPE - IITB - ASSGAB)",
"Atendimento Redes Nível 3 da DTI (PCPE - DTI - UNISUT - SUPTEC)",
"Central de Processamento de Dados do IITB (PCPE - IITB - CPD)",
"Comissão Permanente de Avaliação e Promoção da Carreira de Delegado de Polícia (PCPE - GAB - CAPCD)",
"Coordenação dos Expressos Cidadão (IITB) (PCPE - IITB - EXPRESSOCIDADAO)",
"Delegacia de Polícia de Crimes contra a Ordem Tributária - DRACCO (PCPE - DRACCO - DECCOT)",
"Delegacia de Polícia de Repressão aos Crimes Cibernéticos - DRACCO (PCPE - DRACCO - DPCRICI)",
"Delegacia Interestadual de Capturas - DRACCO (PCPE - DRACCO - CAPTURAS)",
"Departamento de Repressão à Corrupção e ao Crime Organizado - DRACCO (PCPE - DRACCO)",
"DIAG - FUNREPOL (PCPE - DIAG - FUNREPOL)",
"DINTEL - Unidade de Interceptação de Sinais (PCPE - DINTEL - UIS)",
"Divisão Criminal do IITB (PCPE - IITB - DIVCRIM)",
"Divisão de Arquivo Civil (PCPE - IITB - UTICIV - DIVAC)",
"Divisão de Manutenção de Equipamentos (PCPE - DTI - UNIATE - DIVMAE)",
"Divisão Regional de Identificação Civil (PCPE - IITB - GAB - DIRIC)",
"DTI - CONTRATOS (PCPE - DTI - CONTRATOS)",
"Força Tarefa &quot;Caso Beatriz&quot; (PCPE - FT CASO BEATRIZ)",
"Força Tarefa de Combate à Fraudes - IITB (PCPE - IITB - UTICIV - FRAUDES)",
"Gabinete da Gerência do IITB (PCPE - IITB - GABINETE)",
"Grupo de Operações Especiais - DRACCO (PCPE - DRACCO - GOE)",
"Identificação Necropapiloscópica do IITB (PCPE - IITB - IDNECROPAP)",
"IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - ARARIPINA (PCPE - IITB - RASTRO - ARARIP)",
"IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - ARCOVERDE (PCPE - IITB - RASTRO - ARCOV)",
"IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - BELO JARDIM (PCPE - IITB - RASTRO- B JARDIM)",
"IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - CARUARU (PCPE - IITB - RASTRO - CARUARU)",
"IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - GARANHUNS (PCPE - IITB - RASTRO - GARANHU)",
"IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - GRAVATÁ (PCPE - IITB - RASTRO - GRAVATÁ)",
"IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - NAZARÉ DA MATA (PCPE - IITB - RASTRO - NAZARE)",
"IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - PALMARES (PCPE - IITB - RASTRO - PALMARE)",
"IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - PETROLINA (PCPE - IITB - RASTRO - PETROLI)",
"IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - SALGUEIRO (PCPE - IITB - RASTRO - SALGUE)",
"IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - SERRA TALHADA (PCPE - IITB - RASTRO - SERRA T)",
"IITB - UNIDADE CRIMINAL - DIVISÃO DE TÉCNICA DE IDENTIFICAÇÃO CRIMINAL (PCPE - IITB - DIVTEC)",
"Instituto de Identificação Tavares Buril - CEPLANC (PCPE - IITB - IITB.CEPLANC)",
"Instituto de Identificação Tavares Buril - IITB (PCPE - IITB)",
"Núcleo da Diretoria de Tecnologia da Informação na Dinter 2 (PCPE - DTI - DINTER 2)",
"Núcleo de Ações Sociais (PCPE - IITB - UTICIV - NUACS)",
"Núcleo de Identificação de Desaparecidos (PCPE - IITB - UTICIV - NID)",
"Núcleo de Identificação Neonatal (PCPE - IITB - UTICIV -NEONATAL)",
"Núcleo de Inteligência da DPCA (PCPE - DINTEL - NIDPCA)",
"Núcleo de Inteligência do Departamento de Repressão à Corrupção e ao Crime Organizado - DRACCO (PCPE - DRACCO - NIDRACCO)",
"Núcleo de Inteligência do Departamento de Repressão à Corrupção e ao Crime Organizado - NI DRACCO 1 (PCPE - DRACCO - NIDRACCO1)",
"Núcleo de Inteligência do Departamento de Repressão à Corrupção e ao Crime Organizado - NI DRACCO 2 (PCPE - DRACCO - NIDRACCO2)",
"Núcleo de inteligência do DPMUL (PCPE - DINTEL - NIDPMUL)",
"Núcleo de Tecnologia da Informação - Instituto de Identificação Tavares Buril (PCPE - IITB - NTI)",
"PCPE -  DIRH - Divisão de Capacitação (PCPE - DIRH - DIVCA)",
"PCPE - Assessoria da DIRH (PCPE - ASSDIRH)",
"PCPE - Assessoria de Comunicação Social da Polícia Civil (PCPE - ASSCOM)",
"PCPE - Capelania (PCPE - CAPEL)",
"PCPE - Central de  Plantões da  Capital (PCPE - DIM - CEPLANC)",
"PCPE - Comando de Operações e Recursos Especiais da Policia Civil (PCPE - CORE)",
"PCPE - Coord. de Planejamento e Modernização da Policia Civil (PCPE - COPLAM)",
"PCPE - Coord. de Planejamento Operacional (PCPE - CPO)",
"PCPE - Coord. dos Procedimentos Policiais (PCPE - COORDPPOL)",
"PCPE - Coord. dos Procedimentos Policiais - Gab. Chefia de Polícia (PCPE - COORDPPOL - SEGAB)",
"PCPE - Coordenação dos Serviços de Plantão Policial (4Turmas) (PCPE - COORDPLAN)",
"PCPE - COPLAM - Banco de Projetos (PCPE - COPLAM - PROJETOS)",
"PCPE - COPLAM - Lei de Acesso à Informação - LAI (PCPE - COPLAM - LAI)",
"PCPE - COPLAM - Setor de Coordenação, Monitoramento e Avaliação (PCPE - COPLAM - CMA)",
"PCPE - COPLAM - Unidade de Planejamento Estrategico e Gestão - UNIPEG (PCPE - COPLAM - UNIPEG)",
"PCPE - CORE -  GESTAO PROJETOS (PCPE - CORE - PROJETOS)",
"PCPE - CORE - Complexo de Operações da Polícia Civil (PCPE - CORE - COPC)",
"PCPE - CORE - Delegacia de Polícia de Repressão á Intolerância Esportiva (PCPE - CORE - DPRIE)",
"PCPE - CORE - Destruicao de armas apreendidas (PCPE - CORE - DESTRUICAO)",
"PCPE - CORE - Distribuição de Coletes (PCPE - CORE - COLETES)",
"PCPE - CORE - Divisão de Controle de Atividades Licenciadas (PCPE - CORE - DIVCAL)",
"PCPE - CORE - Divisão de Planejamento e Coordenação Operacional (Transportes) (PCPE - CORE - DIVPLAN)",
"PCPE - CORE - Núcleo de Identificação de Arma de Fogo (PCPE - CORE - NIAF)",
"PCPE - CORE - Unidade de Administração, Planejamento e Logística (PCPE - CORE - UNAPLOG)",
"PCPE - CORE - Unidade de Operações Especiais (PCPE - CORE - UNIOPE)",
"PCPE - CORE - Unidade de Operações Táticas (PCPE - CORE - UNIOT)",
"PCPE - CORE - 3º CURSO DE OPERAÇÕES TÁTICAS ESPECIAIS (PCPE - CORE - III COTE)",
"PCPE - Delegacia de Polícia de Atos Infracionais (PCPE - DPCA - DEPAI)",
"PCPE - DENARC - Assessoria da PCPE (PCPE - DENARC - ASSPCPE)",
"PCPE - DENARC - Assessoria do Denarc (PCPE - DENARC - ASSDENARC)",
"PCPE - DENARC - Divisão Administrativa do Denarc (PCPE - DENARC - DIVAD/DENARC)",
"PCPE - DENARC - Divisão De Perícia Criminal (PCPE - DENARC - DIVPEC)",
"PCPE - DENARC - 1ª Delegacia de Polícia de Repressão ao Narcotráfico (PCPE - DENARC - 1ª DPRN)",
"PCPE - DENARC - 2ª Delegacia de Polícia de Repressão ao Narcotráfico (PCPE - DENARC - 2ª DPRN)",
"PCPE - DENARC - 3ª Delegacia de Polícia de Repressão ao Narcotráfico (PCPE - DENARC - 3ª DPRN)",
"PCPE - Departamento  de Repressão  ao Narcotráfico (PCPE - DENARC)",
"PCPE - Departamento de  Repressão aos  Crimes Patrimoniais (PCPE - DEPATRI)",
"PCPE - Departamento de Homicídios e de Proteção à Pessoa (PCPE - DHPP)",
"PCPE - Departamento de Polícia da Criança e do Adolescente (PCPE - DPCA)",
"PCPE - Departamento de Polícia da Mulher (PCPE - DPMUL)",
"PCPE - DEPATRI - Delegacia de Policia de Delitos de Trânsito (PCPE - DEPATRI - DPDT)",
"PCPE - DEPATRI - Delegacia de Policia de Repressão ao Estelionato (PCPE - DEPATRI - DPRE)",
"PCPE - DEPATRI - Delegacia de Policia de Roubos e Furtos (PCPE - DEPATRI - DPRF)",
"PCPE - DEPATRI - Delegacia de Policia de Roubos e Furtos de Cargas (PCPE - DEPATRI - DPRFC)",
"PCPE - DEPATRI - Delegacia de Policia de Roubos e Furtos de Veiculos (PCPE - DEPATRI - DPRFV)",
"PCPE - DEPATRI - Delegacia de Policia do Turista (PCPE - DEPATRI - DPTUR)",
"PCPE - DEPATRI - Divisão Administrativa do DEPATRI (PCPE - DEPATRI - DIVAD/DEPATRI)",
"PCPE - DEPATRI - Divisão de Apoio Operacional (PCPE - DEPATRI - DIVAOP)",
"PCPE - DEPATRI - DPTUR - Setor de Análise e Estatística (PCPE - DEPATRI - DPTUR - ESTAT)",
"PCPE - DEPATRI - DPTUR - Setor de Apoio Administrativo (PCPE - DEPATRI - DPTUR - ADM)",
"PCPE - DEPATRI - DPTUR - Setor de Cartório (PCPE - DEPATRI - DPTUR - CART)",
"PCPE - DEPATRI - DPTUR - Setor de Coordenação Setorial (PCPE - DEPATRI - DPTUR - CSET)",
"PCPE - DEPATRI - DPTUR - Setor de Investigação (PCPE - DEPATRI - DPTUR - INV)",
"PCPE - DEPATRI - Núcleo de Inteligencia do DEPATRI (PCPE - DEPATRI - NIDEPATRI)",
"PCPE - DHPP - Assessoria do DHPP (PCPE - DHPP - ASSDHPP)",
"PCPE - DHPP - Coordenação da Força Tarefa (PCPE - DHPP - CFTDHPP)",
"PCPE - DHPP - Delegacia de Desaparecidos e de Proteção à Pessoa (PCPE - DHPP - DDPP)",
"PCPE - DHPP - Delegacia de Policia do Idoso (PCPE - DHPP - DPI)",
"PCPE - DHPP - Divisão Administrativa do DHPP (PCPE - DHPP - DIVAD/DHPP)",
"PCPE - DHPP - Divisão de Análise e Estatística (PCPE - DHPP - DIVAES)",
"PCPE - DHPP - Divisão de Apoio a Testemunhas e Vitimas de Intolerância (PCPE - DHPP - DIVATVIN)",
"PCPE - DHPP - Divisão de Controle Interno (PCPE - DHPP - DIVCIN)",
"PCPE - DHPP - NÚCLEO DE FORÇA TAREFA DE HOMICÍDIOS (PCPE - DHPP - NFTH)",
"PCPE - DHPP - Plantão da Coordenação da Força Tarefa (PCPE - DHPP - CFTH - PLAN)",
"PCPE - DHPP - 1ª Delegacia de Policia de Homicídios (PCPE - DHPP - 1ª DPH)",
"PCPE - DHPP - 2ª Delegacia de Policia de Homicidios (PCPE - DHPP - 2ª DPH)",
"PCPE - DHPP - 3ª Delegacia de Policia de Homicídios (PCPE - DHPP - 3ª DPH)",
"PCPE - DHPP - 4ª Delegacia de Policia de Homicídios (PCPE - DHPP - 4ª DPH)",
"PCPE - DHPP - 5ª Delegacia de Policia de Homicídios (PCPE - DHPP - 5ª DPH)",
"PCPE - DIAG - Assessoria da Diag (PCPE - DIAG - ASSDIAG)",
"PCPE - DIAG - Assessoria da PCPE (PCPE - DIAG - ASSPCPE)",
"PCPE - DIAG - COMISSÃO PERMANENTE DE ALIENAÇÃO DE BENS (PCPE - DIAG - CPAB)",
"PCPE - DIAG - COMISSÃO PERMANENTE DE AVALIAÇÃO E ALIENAÇÃO DE BENS DO ESTADO DE PERNAMBUCO (PCPE - DIAG - CPAABE)",
"PCPE - DIAG - Comissão Permanente de Licitação (PCPE - DIAG - CPL)",
"PCPE - DIAG - Divisão de Administração e Logística (PCPE - DIAG - DIVALOG)",
"PCPE - DIAG - Divisão de Almoxarifado (PCPE - DIAG - DIVALM)",
"PCPE - DIAG - Divisão de Arquivo Geral (PCPE - DIAG - DIVAG)",
"PCPE - DIAG - Divisão de Compras (PCPE - DIAG - DIVCOMPRAS)",
"PCPE - DIAG - Divisão de Contabilidade (PCPE - DIAG - DIVCON)",
"PCPE - DIAG - Divisão de Depósito de Bens Apreendidos (PCPE - DIAG - DIVDEBA)",
"PCPE - DIAG - Divisão de Fiscalização de Obras, Laudos de Avaliação de Projetos de Arquitetura e Engenharia (PCPE - DIAG - DIVFLAPE)",
"PCPE - DIAG - Divisão de Manutenção (PCPE - DIAG - DIVMAN)",
"PCPE - DIAG - Divisão de Planejamento e Programação (PCPE - DIAG - DIVPPRO)",
"PCPE - DIAG - Divisão de Prestação de Contas (PCPE - DIAG - DIVPREST)",
"PCPE - DIAG - Divisão de Protocolo da DIAG (PCPE - DIAG - DIVPROT/DIAG)",
"PCPE - DIAG - Divisão de Suprimento e Patrimônio (PCPE - DIAG - DIVSUP)",
"PCPE - DIAG - Divisão de Tesouraria (PCPE - DIAG - DIVTES)",
"PCPE - DIAG - Gabinete Diárias (PCPE - DIAG - GABDIARIAS)",
"PCPE - DIAG - Gráfica da Unidade de Serviços Gerais (PCPE - DIAG - UNISERG-GRÁFICA)",
"PCPE - DIAG - Setor de Diárias (PCPE - DIAG - DIARIAS)",
"PCPE - DIAG - SETOR DE PLANEJAMENTO E ANÁLISE DAS CONTRATAÇÕES PÚBLICAS (PCPE - DIAG - SPACP)",
"PCPE - DIAG - Setor de Suprimentos (PCPE - DIAG - SUPRIMENTOS)",
"PCPE - DIAG - TERMO DE REFERÊNCIA (PCPE - DIAG - TERMOREF)",
"PCPE - DIAG - Unidade de Água da UNEATEM (PCPE - DIAG - UNEATEM - AGUA)",
"PCPE - DIAG - Unidade de Energia Elétrica, Água e Telefonia Movél (PCPE - DIAG - UNEATEM)",
"PCPE - DIAG - Unidade de Energia Elétrica da UNEATEM (PCPE - DIAG - UNEATEM - ENERG)",
"PCPE - DIAG - Unidade de Execução Financeira (PCPE - DIAG - UNEFIN)",
"PCPE - DIAG - Unidade de Planejamento e Orçamento (PCPE - DIAG - UNIPLANOR)",
"PCPE - DIAG - Unidade de Projetos de Arquitetura e Engenharia (PCPE - DIAG - UNIPAE)",
"PCPE - DIAG - Unidade de Serviços Gerais (PCPE - DIAG - UNISERG)",
"PCPE - DIAG - Unidade de Telefonia Móvel da UNEATEM (PCPE - DIAG - UNEATEM - TMOVEL)",
"PCPE - DIAG - Unidade de Transportes e Oficina (PCPE - DIAG - UNITOF)",
"PCPE - DIAG - UNISERG - CÉLULA DE CONTROLE E REGISTRO DE BENS IMÓVEIS (PCPE - DIAG - UNISERG - CCRBI)",
"PCPE - DIAG - UNISERG - CÉLULA DE CONTROLE E REGISTRO DE BENS MÓVEIS (PCPE - DIAG - UNISERG - CCRBM)",
"PCPE - DIAG - UNITOF - Divisão de Controle de Abastecimentos e Serviços (PCPE - DIAG - UNITOF - DICAS)",
"PCPE - DIAG - UNITOF - Divisão de Manutenção e Controle de Veículos (PCPE - DIAG - UNITOF - DIMAVE)",
"PCPE - DIAG - UNITOF - Remoção de Veículos (PCPE - DIAG - UNITOF - REMOVE)",
"PCPE - DIAG - UNITOF - SA - Setor Administrativo (PCPE - DIAG - UNITOF - SA)",
"PCPE - DIAG - UNITOF - Setor de Controle de Multas (PCPE - DIAG - UNITOF - MULTAS)",
"PCPE - DIM - Delegacia de Polícia da 1ª Circunscrição - Rio Branco (PCPE - DIM - DP 1ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 10ª Circunscrição - Ibura (PCPE - DIM - DP 10ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 11ª Circunscrição - Afogados (PCPE - DIM - DP 11ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 12ª Circunscrição - Jardim São Paulo (PCPE - DIM - DP 12ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 13ª Circunscrição - Mustardinha (PCPE - DIM - DP 13ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 14ª Circunscrição - Várzea (PCPE - DIM - DP 14ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 15ª Circunscrição - Alto Pascoal (PCPE - DIM - DP 15ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 16ª Circunscrição - Água Fria (PCPE - DIM - DP 16ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 17ª Circunscrição - Vasco da Gama (PCPE - DIM - DP 17ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 18ª Circunscrição - Macaxeira (PCPE - DIM - DP 18ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 2ª Circunscrição - Boa Vista (PCPE - DIM - DP 2ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 20ª Circunscrição - Jaboatão dos Guararapes (PCPE - DIM - DP 20ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 21ª Circunscrição - Moreno (PCPE - DIM - DP 21ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 22ª Circunscrição - Piedade (PCPE - DIM - DP 22ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 23ª Circunscrição - Cavaleiro (PCPE - DIM - DP 23ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 24ª Circunscrição - Varadouro (PCPE - DIM - DP 24ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 25ª Circunscrição - Peixinhos (PCPE - DIM - DP 25ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 26ª Circunscrição - Rio Doce (PCPE - DIM - DP 26ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 27ª Circunscrição - Abreu e Lima (PCPE - DIM - DP 27ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 28ª Circunscrição - Paulista (PCPE - DIM - DP 28ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 29ª Circunscrição - Igarassu (PCPE - DIM - DP 29ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 3ª Circunscrição - Joana Bezerra (PCPE - DIM - DP 3ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 30ª Circunscrição - Itamaracá (PCPE - DIM - DP 30ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 31ª Circunscrição - Itapissuma (PCPE - DIM - DP 31ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 32ª Circunscrição - Engenho Maranguape (PCPE - DIM - DP 32ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 33ª Circunscrição - Cruz de Rebouças (PCPE - DIM - DP 33ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 34ª Circunscrição - Maria de Farinha (PCPE - DIM - DP 34ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 35ª Circunscrição - Araçoiaba (PCPE - DIM - DP 35ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 37ª Circunscrição - Camaragibe (PCPE - DIM - DP 37ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 38ª Circunscrição - São Lourenço da Mata (PCPE - DIM - DP 38ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 39ª Circunscrição - Aldeia (PCPE - DIM - DP 39ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 4ª Circunscrição - Espinheiro (PCPE - DIM - DP 4ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 40ª Circunscrição - Cabo de Santo Agostinho (PCPE - DIM - DP 40ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 41ª Circunscrição - Ponte dos Carvalhos (PCPE - DIM - DP 41ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 42ª Circunscrição - Ipojuca (PCPE - DIM - DP 42ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 43ª Circunscrição - Porto de Galinhas (PCPE - DIM - DP 43ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 5ª Circunscrição - Casa Amarela (PCPE - DIM - DP 5ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 6ª Circunscrição - Cordeiro (PCPE - DIM - DP 6ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 7ª Circunscrição - Boa Viagem (PCPE - DIM - DP 7ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 8ª Circunscrição - Jordão (PCPE - DIM - DP 8ª CIRC)",
"PCPE - DIM - Delegacia de Polícia da 9ª Circunscrição - Ipsep (PCPE - DIM - DP 9ª CIRC)",
"PCPE - DIM - Divisão de ADM., Planejamento e Logistica da Metropolitana (PCPE - DIM - DIVAPLOM)",
"PCPE - DIM - Divisão de Planejamento Operacional Metropolitano (PCPE - DIM - DIVPLOM)",
"PCPE - DIM - Gerencia de Controle Operacional Metropolitano da Policia Civil (PCPE - DIM - GCOM)",
"PCPE - DIM - Plantão da Delegacia de Polícia da 40ª Circunscrição - Cabo de Santo Agostinho - 1ª Chefia (PCPE - DIM - 40ª CIRC - EQ 1)",
"PCPE - DIM - Plantão da Delegacia de Polícia da 40ª Circunscrição - Cabo de Santo Agostinho - 2ª Chefia (PCPE - DIM - 40ª CIRC - EQ 2)",
"PCPE - DIM - Plantão da Delegacia de Polícia da 40ª Circunscrição - Cabo de Santo Agostinho - 3ª Chefia (PCPE - DIM - 40ª CIRC - EQ 3)",
"PCPE - DIM - Plantão da Delegacia de Polícia da 40ª Circunscrição - Cabo de Santo Agostinho - 4ª Chefia (PCPE - DIM - 40ª CIRC - EQ 4)",
"PCPE - DIM - 1ª Delegacia de Polícia da 19ª Circunscrição - Prazeres (PCPE - DIM - 1ª DP 19ª CIRC)",
"PCPE - DIM - 1ª Delegacia Seccional de Policia - Stº Amaro (PCPE - DIM - 1ª DESEC)",
"PCPE - DIM - 1ª Equipe de Plantão da 19ª Circunscrição - Prazeres (PCPE - DIM - 19 CIRC - EQ 1)",
"PCPE - DIM - 1ª Equipe de Plantão da 28ª Circunscrição  - Paulista (PCPE - DIM - 28 CIRC - EQ 1)",
"PCPE - DIM - 1ª EQUIPE DO PLANTÃO DA 7ª CIRC - BOA VIAGEM (PCPE - DIM - 7ª CIRC - EQ 1)",
"PCPE - DIM - 10ª Delegacia Seccional de Policia - Cabo de Stº Agostinho (PCPE - DIM - 10ª DESEC)",
"PCPE - DIM - 2ª Delegacia de Polícia da 19ª Circunscrição - Muribeca (PCPE - DIM - 2ª DP 19ª CIRC)",
"PCPE - DIM - 2ª Delegacia Seccional de Policia - Espinheiro (PCPE - DIM - 2ª DESEC)",
"PCPE - DIM - 2ª Equipe de Plantão da 19ª Circunscrição - Prazeres (PCPE - DIM - 19 CIRC - EQ 2)",
"PCPE - DIM - 2ª Equipe de Plantão da 28ª Circunscrição  - Paulista (PCPE - DIM - 28 CIRC - EQ 2)",
"PCPE - DIM - 2ª EQUIPE DO PLANTÃO DA 7ª CIRC - BOA VIAGEM (PCPE - DIM - 7ª CIRC - EQ 2)",
"PCPE - DIM - 3ª Equipe de Plantão da 19ª Circunscrição - Prazeres (PCPE - DIM - 19 CIRC - EQ 3)",
"PCPE - DIM - 3ª Equipe de Plantão da 28ª Circunscrição  - Paulista (PCPE - DIM - 28 CIRC - EQ 3)",
"PCPE - DIM - 3ª EQUIPE DO PLANTÃO DA 7ª CIRC - BOA VIAGEM (PCPE - DIM - 7ª CIRC - EQ 3)",
"PCPE - DIM - 4ª Delegacia Seccional de Policia - Várzea (PCPE - DIM - 4ª DESEC)",
"PCPE - DIM - 4ª Equipe de Plantão da 19ª Circunscrição - Prazeres (PCPE - DIM - 19 CIRC - EQ 4)",
"PCPE - DIM - 4ª Equipe de Plantão da 28ª Circunscrição  - Paulista (PCPE - DIM - 28 CIRC - EQ 4)",
"PCPE - DIM - 4ª EQUIPE DO PLANTÃO DA 7ª CIRC - BOA VIAGEM (PCPE - DIM - 7ª CIRC - EQ 4)",
"PCPE - DIM - 5ª Delegacia Seccional de Policia - Apipucos (PCPE - DIM - 5ª DESEC)",
"PCPE - DIM - 6ª Delegacia Seccional de Policia - Jaboatão dos Guararapes (PCPE - DIM - 6ª DESEC)",
"PCPE - DIM - 7ª Delegacia Seccional de Policia - Olinda (PCPE - DIM - 7ª DESEC)",
"PCPE - DIM - 8ª Delegacia Seccional de Policia - Paulista (PCPE - DIM - 8ª DESEC)",
"PCPE - DIM - 9ª Delegacia Seccional de Policia - São Lourenço da Mata (PCPE - DIM - 9ª DESEC)",
"PCPE - DINTEL -  NÚCLEO CELLEBRITE AGRESTE (PCPE - DINTEL - CELLEBRITE AGR)",
"PCPE - DINTEL - Coordenação da Inteligência da Polícia Civil (PCPE - DINTEL - COORDINTEL)",
"PCPE - DINTEL - Coordenadoria da PCPE (PCPE - DINTEL - COORPCPE)",
"PCPE - DINTEL - Divisão de Análises (PCPE - DINTEL - DIVA)",
"PCPE - DINTEL - Divisão de Análises do NI da 26º Delegacia Seccional de Polícia de Petrolina (PCPE-DINTER2-NI26ª DESEC-DIVA)",
"PCPE - DINTEL - Divisão de Documentação (PCPE - DINTEL - DIVDOC)",
"PCPE - DINTEL - Divisão de Operações (PCPE - DINTEL - DIVOP)",
"PCPE - DINTEL - Divisão de Operações do NI da 26º Delegacia Seccional de Polícia de Petrolina (PCPE-DINTER2-NI26ª DESEC-DIVOP)",
"PCPE - DINTEL - Laboratório de Tecnologia Contra a Lavagem de Dinheiro (PCPE - DINTEL - LABLD)",
"PCPE - DINTEL - Laboratório de Tecnologia Contra a Lavagem de Dinheiro - Análise (PCPE - DINTEL - LABLD-ANALISE)",
"PCPE - DINTEL - Laboratório de Tecnologia Contra a Lavagem de Dinheiro - Caruaru (PCPE - DINTEL - LABLD CARUARU)",
"PCPE - DINTEL - NÚCLEO CELLEBRITE RECIFE (PCPE - DINTEL - CELLEBRITE REC)",
"PCPE - DINTEL - Nucleo de Inteligencia  da DIM (PCPE - DINTEL - NIDIM)",
"PCPE - DINTEL - Núcleo de Inteligência da Delegacia de Polícia de Crimes contra a Adm e Serviços Públicos (PCPE - DINTEL - NIDECASP)",
"PCPE - DINTEL - Núcleo de Inteligência da Delegacia de Polícia de Crimes contra a Ordem Pública (PCPE - DINTEL - NIDECCOT)",
"PCPE - DINTEL - Núcleo de Inteligência da Gerência de Controle Operacional Especializada (PCPE - DINTEL - NIGCOE)",
"PCPE - DINTEL - Núcleo de Inteligência da Zona da Mata Norte (PCPE - DINTEL - NIZM)",
"PCPE - DINTEL - Núcleo de Inteligência da 11º Delegacia Seccional de Polícia de Goiana (PCPE - DINTEL - NI11ªDES/DITR1)",
"PCPE - DINTEL - Núcleo de Inteligência da 14º DESEC (Caruaru) e 18ª DESEC (Garanhuns) (PCPE - DINTEL - NI14ª-18ªDESEC)",
"PCPE - DINTEL - Núcleo de Inteligência da 23º Delegacia Seccional de Polícia de Salgueiro (PCPE - DINTEL - NI23ªDES/DITR1)",
"PCPE - DINTEL - Núcleo de Inteligência da 26º Delegacia Seccional de Polícia de Petrolina (PCPE-DINTER2-NI26ª DESEC/DNTR2)",
"PCPE - DINTEL - Núcleo de Inteligência do Departamento de Homicídios e de Proteção a Pessoa (PCPE - DINTEL - NIDHPP)",
"PCPE - DINTEL - Núcleo de Inteligência do Departamento de Repressão ao Narcotráfico (PCPE - DINTEL - NIDENARC)",
"PCPE - DINTEL - Núcleo de Inteligência do Departamento de Repressão aos Crimes Patrimoniais (PCPE - DINTEL - NIDEPATRI)",
"PCPE - DINTEL - Núcleo de Inteligência do Grupo de Operações Especiais (PCPE - DINTEL - NIGOE)",
"PCPE - DINTEL - Unidade de Apoio Administrativo (PCPE - DINTEL - UAA)",
"PCPE - DINTEL - Unidade de Busca Eletrônica (PCPE - DINTEL - UBE)",
"PCPE - DINTEL - Unidade de ContraInteligência (PCPE - DINTEL - UCI)",
"PCPE - DINTEL - Unidade de Crime Organizado (PCPE - DINTEL - UCO)",
"PCPE - DINTEL - Unidade de Operações e Inteligência (PCPE - DINTEL - UOP)",
"PCPE - DINTEL - Unidade de Tecnologia de Análise (PCPE - DINTEL - UTA)",
"PCPE - DINTER 1 -  Delegacia de Policia da 100ª Circunscrição - Camocim de São Félix (PCPE - DINTER 1 - DP 100ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 101ª Circunscrição - Sairé (PCPE - DINTER 1 - DP 101ªCIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 102ª Circunscrição - Barra de Guabiraba (PCPE - DINTER 1 - DP 102ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 103ª Circunscrição - Ibirajuba (PCPE - DINTER 1 - DP 103ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 107ª Circunscrição - Brejo da Madre de Deus (PCPE - DINTER 1 - DP 107ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 111ª Circunscrição - Jataúba (PCPE - DINTER 1 - DP 111ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 128ª Circunscrição - Sta. Cruz do Capibaribe (PCPE - DINTER 1 - DP 128ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 129ª Circunscrição - Toritama (PCPE - DINTER 1 - DP 129ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 130ª Circunscrição - Taquaritinga do Norte (PCPE - DINTER 1 - DP 130ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 131ª Circunscrição - Vertentes (PCPE - DINTER 1 - DP 131ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 134ª Circunscrição - Garanhuns (PCPE - DINTER 1 - DP 134ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 135ª Circunscrição - Garanhuns (PCPE - DINTER 1 - DP 135ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 136ª Circunscrição - Bom Conselho (PCPE - DINTER 1 - DP 136ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 137ª Circunscrição - Águas Belas (PCPE - DINTER 1 - DP 137ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 138ª Circunscrição - Lajedo (PCPE - DINTER 1 - DP 138ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 139ª Circunscrição - Canhotinho (PCPE - DINTER 1 - DP 139ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 140ª Circunscrição - Caetés (PCPE - DINTER 1 - DP 140ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 141ª Circunscrição - São João (PCPE - DINTER 1 - DP 141ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 142ª Circunscrição - Capoeiras (PCPE - DINTER 1 - DP 142ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 143ª Circunscrição - Iati (PCPE - DINTER 1 - DP 143ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 144ª Circunscrição - Correntes (PCPE - DINTER 1 - DP 144ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 145ª Circunscrição - Saloá (PCPE - DINTER 1 - DP 145ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 146ª Circunscrição - Jurema (PCPE - DINTER 1 - DP 146ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 147ª Circunscrição - Jupi (PCPE - DINTER 1 - DP 147ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 148ª Circunscrição - Calçados (PCPE - DINTER 1 - DP 148ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 149ª Circunscrição - Lagoa do Ouro (PCPE - DINTER 1 - DP 149ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 150ª Circunscrição - Paranatama (PCPE - DINTER 1 - DP 150ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 151ª Circunscrição - Jucati (PCPE - DINTER 1 - DP 151ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 152ª Circunscrição - Palmerina (PCPE - DINTER 1 - DP 152ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 153ª Circunscrição - Angelim (PCPE - DINTER 1 - DP 153ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 154ª Circunscrição - Brejão (PCPE - DINTER 1 - DP 154ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 155ª Circunscrição - Terezinha (PCPE - DINTER 1 - DP 155ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 80ª Circunscrição - Joaquim Nabuco (PCPE - DINTER 1 - DP 80ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 81ª Circunscrição - Maraial (PCPE - DINTER 1 - DP 81ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 82ª Circunscrição - São José da Coroa Grande (PCPE - DINTER 1 - DP 82ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 83ª Circunscrição - Xexéu (PCPE - DINTER 1 - DP 83ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 84ª Circunscrição - Cortês (PCPE - DINTER 1 - DP 84ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 85ª Circunscrição - Jaqueira (PCPE - DINTER 1 - DP 85ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 86ª Circunscrição - Belém de Maria (PCPE - DINTER 1 - DP 86ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 87ª Circunscrição - São Benedito do Sul (PCPE - DINTER 1 - DP 87ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 88ª Circunscrição - Caruaru (PCPE - DINTER 1 - DP 88ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 89ª Circunscrição - Caruaru (PCPE - DINTER 1 - DP 89ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 90ª Circunscrição - Caruaru (PCPE - DINTER 1 - DP 90ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 91ª Circunscrição - Bezerros (PCPE - DINTER 1 - DP 91ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 92ª Circunscrição - Bonito (PCPE - DINTER 1 - DP 92ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 93ª Circunscrição - Panelas (PCPE - DINTER 1 - DP 93ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 94ª Circunscrição - Cupira (PCPE - DINTER 1 - DP 94ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 95ª Circunscrição - Altinho (PCPE - DINTER 1 - DP 95ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 96ª Circunscrição - Agrestina (PCPE - DINTER 1 - DP 96ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 97ª Circunscrição - São Joaquim do Monte (PCPE - DINTER 1 - DP 97ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 98ª Circunscrição - Riacho das Almas (PCPE - DINTER 1 - DP 98ª CIRC)",
"PCPE - DINTER 1 -  Delegacia de Policia da 99ª Circunscrição - Lagoa dos Gatos (PCPE - DINTER 1 - DP 99ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 104ª Circunscrição - Belo Jardim (PCPE - DINTER 1 - DP 104ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 105ª Circunscrição - Pesqueira (PCPE - DINTER 1 - DP 105ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 106ª Circunscrição - São Bento (PCPE - DINTER 1 - DP 106ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 108ª Circunscrição - São Caetano (PCPE - DINTER 1 - DP 108ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 109ª Circunscrição - Cachoeirinha (PCPE - DINTER 1 - DP 109ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 110ª Circunscrição - Sanharó (PCPE - DINTER 1 - DP 110ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 112ª Circunscrição - Tacaimbó (PCPE - DINTER 1 - DP 112ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 113ª Circunscrição - Alagoinha (PCPE - DINTER 1 - DP 113ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 114ª Circunscrição - Poção (PCPE - DINTER 1 - DP 114ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 115ª Circunscrição - Limoeiro (PCPE - DINTER 1 - DP 115ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 116ª Circunscrição - Surubim (PCPE - DINTER 1 - DP 116ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 117ª Circunscrição - Bom Jardim (PCPE - DINTER 1 - DP 117ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 118ª Circunscrição - Passira (PCPE - DINTER 1 - DP 118ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 119ª Circunscrição - Cumaru (PCPE - DINTER 1 - DP 119ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 120ª Circunscrição - João Alfredo (PCPE - DINTER 1 - DP 120ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 121ª Circunscrição - Orobó (PCPE - DINTER 1 - DP 121ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 122ª Circunscrição - Feira Nova (PCPE - DINTER 1 - DP 122ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 123ª Circunscrição - São Vicente Férrer (PCPE - DINTER 1 - DP 123ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 124ª Circunscrição - Casinhas (PCPE - DINTER 1 - DP 124ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 125ª Circunscrição - Machados (PCPE - DINTER 1 - DP 125ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 126ª Circunscrição - Vertente do Lério (PCPE - DINTER 1 - DP 126ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 127ª Circunscrição - Salgadinho (PCPE - DINTER 1 - DP 127ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 132ª Circunscrição - Frei Miguelinho (PCPE - DINTER 1 - DP 132ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Polícia da 133ª Circunscrição - Sta Maria do Cabumcá (PCPE - DINTER 1 - DP 133ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 45ª Circunscrição - Carpina (PCPE - DINTER 1 - DP 45ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 46ª Circunscrição - Timbaúba (PCPE - DINTER 1 - DP 46ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 47ª Circunscrição - Paudalho (PCPE - DINTER 1 - DP 47ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 48ª Circunscrição - Aliança (PCPE - DINTER 1 - DP 48ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 49ª Circunscrição - Itambé (PCPE - DINTER 1 - DP 49ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 50ª Circunscrição - Nazaré da Mata (PCPE - DINTER 1 - DP 50ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 51ª Circunscrição - Vicência (PCPE - DINTER 1 - DP 51ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 52ª Circunscrição - Macaparana (PCPE - DINTER 1 - DP 52ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 53ª Circunscrição - Condado (PCPE - DINTER 1 - DP 53ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 54ª Circunscrição - Lagoa de Itaenga (PCPE - DINTER 1 - DP 54ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 55ª Circunscrição - Itaquitinga (PCPE - DINTER 1 - DP 55ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 56ª Circunscrição - Lagoa do Carro (PCPE - DINTER 1 - DP 56ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 57ª Circunscrição - Tracunhém (PCPE - DINTER 1 - DP 57ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 58ª Circunscrição - Buenos Aires (PCPE - DINTER 1 - DP 58ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 59ª Circunscrição - Ferreiros (PCPE - DINTER 1 - DP 59ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 60ª Circunscrição - Camuntanga (PCPE - DINTER 1 - DP 60ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 61ª Circunscrição - Vitoria de Stº Antão (PCPE - DINTER 1 - DP 61ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 62ª Circunscrição - Gravatá (PCPE - DINTER 1 - DP 62ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 63ª Circunscrição - Escada (PCPE - DINTER 1 - DP 63ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 64ª Circunscrição - Glória do Goitá (PCPE - DINTER 1 - DP 64ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 65ª Circunscrição - Pombos (PCPE - DINTER 1 - DP 65ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 66ª Circunscrição - Amaraji (PCPE - DINTER 1 - DP 66ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 67ª Circunscrição - Chã Grande (PCPE - DINTER 1 - DP 67ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 68ª Circunscrição - Primavera (PCPE - DINTER 1 - DP 68ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 69ª Circunscrição - Chã de Alegria (PCPE - DINTER 1 - DP 69ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 71ª Circunscrição - Ribeirão (PCPE - DINTER 1 - DP 71ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 72ª Circunscrição - Barreiros (PCPE - DINTER 1 - DP 72ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 73ª Circunscrição - Sirinhaém (PCPE - DINTER 1 - DP 73ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 74ª Circunscrição - Catende (PCPE - DINTER 1 - DP 74ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 75ª Circunscrição - Água Preta (PCPE - DINTER 1 - DP 75ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 76ª Circunscrição - Gameleira (PCPE - DINTER 1 - DP 76ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 77ª Circunscrição - Quipapá (PCPE - DINTER 1 - DP 77ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 78ª Circunscrição - Rio Formoso (PCPE - DINTER 1 - DP 78ª CIRC)",
"PCPE - DINTER 1 - Delegacia de Policia da 79ª Circunscrição - Tamandaré (PCPE - DINTER 1 - DP 79ª CIRC)",
"PCPE - DINTER 1 - Gerência de Controle Operacional do Interior 1 da Polícia Civil (PCPE - DINTER 1 - GCOI 1)",
"PCPE - DINTER 1 - Plantão da 11ª DESEC - Goiana (PCPE - 11ª DESEC - PLANTÃO)",
"PCPE - DINTER 1 - Plantão da 12ª DESEC - Vitória de Santo Antão (PCPE - 12ª DESEC - PLANTÃO)",
"PCPE - DINTER 1 - Prococolo da 14ª Delegacia Seccional de Polícia - Caruaru (PCPE - 14ª DESEC - PROTOCOLO)",
"PCPE - DINTER 1 - Setor Malhas da Lei da 14ª Delegacia Seccional de Caruaru (PCPE - 14ª DESEC - MALHAS)",
"PCPE - DINTER 1 - 1ª  Delegacia de Policia da 44ª Circunscrição - Goiana (PCPE - DINTER 1-1ª DP 44ª CIRC)",
"PCPE - DINTER 1 - 1ª EQ - PLANTÃO DA 90ª CIRC - CARUARU (PCPE - DINTER 1 - 90CIRC-EQ1)",
"PCPE - DINTER 1 - 11ª Delegacia Seccional de Policia - Goiana (PCPE - DINTER 1 - 11ª DESEC)",
"PCPE - DINTER 1 - 12ª Delegacia Seccional de Policia - Vitória de Stº Antão (PCPE - DINTER 1 - 12ª DESEC)",
"PCPE - DINTER 1 - 13ª Delegacia Seccional de Polícia - Palmares (PCPE - DINTER 1 - 13ª DESEC)",
"PCPE - DINTER 1 - 14ª Delegacia Seccional de Polícia - Caruaru (PCPE - DINTER 1 - 14ª DESEC)",
"PCPE - DINTER 1 - 14ª DESEC - SETOR DE PÁTIO (PCPE - DINTER 1 - 14ª D-PÁTIO)",
"PCPE - DINTER 1 - 15ª Delegacia Seccional de Polícia de Belo Jardim (PCPE - DINTER 1 - 15ª DESEC)",
"PCPE - DINTER 1 - 15ª Delegacia Seccional de Polícia de Belo Jardim - PLANTÃO (PCPE - 15ª DESEC - PLANTÃO)",
"PCPE - DINTER 1 - 16ª Delegacia Seccional de Polícia de Limoeiro (PCPE - DINTER 1 - 16ª DESEC)",
"PCPE - DINTER 1 - 17ª Delegacia Seccional de Polícia - Sta Cruz do Capibaribe (PCPE - DINTER 1 - 17ª DESEC)",
"PCPE - DINTER 1 - 18ª Delegacia Seccional de Polícia - Garanhuns (PCPE - DINTER 1 - 18ª DESEC)",
"PCPE - DINTER 1 - 2ª  Delegacia de Policia da 44ª Circunscrição - Ponta de Pedras (PCPE - DINTER 1-2ª DP 44ª CIRC)",
"PCPE - DINTER 1 - 2ª EQ - PLANTÃO DA 90ª CIRC - CARUARU (PCPE - DINTER 1 - 90CIRC-EQ2)",
"PCPE - DINTER 1 - 3ª EQ - PLANTÃO DA 90ª CIRC - CARUARU (PCPE - DINTER 1 - 90CIRC-EQ3)",
"PCPE - DINTER 1 - 4ª EQ - PLANTÃO DA 90ª CIRC - CARUARU (PCPE - DINTER 1 - 90CIRC-EQ4)",
"PCPE - DINTER 2 -  Núcleo de Inteligencia da 23ª da Delegacia Seccional de Policia - Salgueiro (PCPE-DINTER 2- NI23ªDESC/DNTR2)",
"PCPE - DINTER 2 - Delegacia de Plantão da 213ª Circunscrição - Petrolina - 1ª EQ (PCPE - DINTER 2 - 213ª - EQ 1)",
"PCPE - DINTER 2 - Delegacia de Plantão da 213ª Circunscrição - Petrolina - 2ª EQ (PCPE - DINTER 2 - 213ª - EQ 2)",
"PCPE - DINTER 2 - Delegacia de Plantão da 213ª Circunscrição - Petrolina - 3ª EQ (PCPE - DINTER 2 - 213ª - EQ 3)",
"PCPE - DINTER 2 - Delegacia de Plantão da 213ª Circunscrição - Petrolina - 4ª EQ (PCPE - DINTER 2 - 213ª - EQ 4)",
"PCPE - DINTER 2 - Delegacia de Polícia da 156ª Circunscrição - Arcoverde (PCPE - DINTER 2 - DP 156ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 157ª Circunscrição - Buique (PCPE - DINTER 2 - DP 157ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 158ª Circunscrição - Sertânia (PCPE - DINTER 2 - DP 158ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 159ª Circunscrição - Custódia (PCPE - DINTER 2 - DP 159ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 160ª Circunscrição - Itaíba (PCPE - DINTER 2 - DP 160ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 161ª Circunscrição - Ibimirim (PCPE - DINTER 2 - DP 161ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 162ª Circunscrição - Tupanatinga (PCPE - DINTER 2 - DP 162ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 163ª Circunscrição - Pedra (PCPE - DINTER 2 - DP 163ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 164ª Circunscrição - Venturosa (PCPE - DINTER 2 - DP 164ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 165ª Circunscrição - Inajá (PCPE - DINTER 2 - DP 165ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 166ª Circunscrição - Manari (PCPE - DINTER 2 - DP 166ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 167ª Circunscrição - Afogados da Ingazeira (PCPE - DINTER 2 - DP 167ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 168ª Circunscrição - São José do Egito (PCPE - DINTER 2 - DP 168ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 169ª Circunscrição - Tabira (PCPE - DINTER 2 - DP 169ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 170ª Circunscrição - Itapetim (PCPE - DINTER 2 - DP 170ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 171ª Circunscrição - Iguaraci (PCPE - DINTER 2 - DP 171ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 172ª Circunscrição - Santa Terezinha (PCPE - DINTER 2 - DP 172ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 173ª Circunscrição - Tuparetama (PCPE - DINTER 2 - DP 173ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 174ª Circunscrição - Brejinho (PCPE - DINTER 2 - DP 174ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 175ª Circunscrição - Solidão (PCPE - DINTER 2 - DP 175ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 176ª Circunscrição - Ingazeira (PCPE - DINTER 2 - DP 176ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 177ª Circunscrição - Serra Talhada (PCPE - DINTER 2 - DP 177ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 178ª Circunscrição - São José do Belmonte (PCPE - DINTER 2 - DP 178ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 179ª Circunscrição - Flores (PCPE - DINTER 2 - DP 179ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 180ª Circunscrição - Carnaíba (PCPE - DINTER 2 - DP 180ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 181ª Circunscrição - Triunfo (PCPE - DINTER 2 - DP 181ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 182ª Circunscrição - Betânia (PCPE - DINTER 2 - DP 182ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 183ª Circunscrição - Santa Cruz da Baixa Verde (PCPE - DINTER 2 - DP 183ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 184ª Circunscrição - Calumbi (PCPE - DINTER 2 - DP 184ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 185ª Circunscrição - Quixaba (PCPE - DINTER 2 - DP 185ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 186ª Circunscrição - Petrolândia (PCPE - DINTER 2 - DP 186ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 187ª Circunscrição - Floresta (PCPE - DINTER 2 - DP 187ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 188ª Circunscrição - Belém de São Francisco (PCPE - DINTER 2 - DP 188ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 189ª Circunscrição - Tacaratu (PCPE - DINTER 2 - DP 189ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 190ª Circunscrição - Jatobá (PCPE - DINTER 2 - DP 190ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 191ª Circunscrição - Carnaubeira da Penha (PCPE - DINTER 2 - DP 191ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 192ª Circunscrição - Itacuruba (PCPE - DINTER 2 - DP 192ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 193ª Circunscrição - Salgueiro (PCPE - DINTER 2 - DP 193ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 194ª Circunscrição - Parnamarim (PCPE - DINTER 2 - DP 194ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 195ª Circunscrição - Serrita (PCPE - DINTER 2 - DP 195ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 196ª Circunscrição - Mirandiba (PCPE - DINTER 2 - DP 196ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 197ª Circunscrição - Cedro (PCPE - DINTER 2 - DP 197ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 198ª Circunscrição - Verdejante (PCPE - DINTER 2 - DP 198ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 199ª Circunscrição - Terra Nova (PCPE - DINTER 2 - DP 199ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 200ª Circunscrição - Araripina (PCPE - DINTER 2 - DP 200ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 201ª Circunscrição - Ouricuri (PCPE - DINTER 2 - DP 201ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 202ª Circunscrição - Exu (PCPE - DINTER 2 - DP 202ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 203ª Circunscrição - Bodocó (PCPE - DINTER 2 - DP 203ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 204ª Circunscrição - Ipubi (PCPE - DINTER 2 - DP 204ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 205ª Circunscrição - Trindade (PCPE - DINTER 2 - DP 205ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 206ª Circunscrição - Sta. Filomena (PCPE - DINTER 2 - DP 206ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 207ª Circunscrição - Sta. Cruz da Malta (PCPE - DINTER 2 - DP 207ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 208ª Circunscrição - Moreilândia (PCPE - DINTER 2 - DP 208ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 209ª Circunscrição - Granito (PCPE - DINTER 2 - DP 209ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 210ª Circunscrição - Sta Mª da Boa Vista (PCPE - DINTER 2 - DP 210ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 211ª Circunscrição - Cabrobó (PCPE - DINTER 2 - DP 211ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 212ª Circunscrição - Orocó (PCPE - DINTER 2 - DP 212ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 213ª Circunscrição - Petrolina (PCPE - DINTER 2 - DP 213ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 214ª Circunscrição - Petrolina (PCPE - DINTER 2 - DP 214ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 215ª Circunscrição - Lagoa Grande (PCPE - DINTER 2 - DP 215ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 216ª Circunscrição - Afrânio (PCPE - DINTER 2 - DP 216ª CIRC)",
"PCPE - DINTER 2 - Delegacia de Polícia da 217ª Circunscrição - Dormentes (PCPE - DINTER 2 - DP 217ª CIRC)",
"PCPE - DINTER 2 - Divisão de Adm., Planejamento e Logística do Interior 2 (PCPE - DINTER 2 - DIVAPLIN 2)",
"PCPE - DINTER 2 - Divisão de Planejamento do Interior 2 (PCPE - DINTER 2 - DIVPLOI 2)",
"PCPE - DINTER 2 - Plantão da 20ª DESEC - Afogados da Ingazeira (PCPE - 20ª DESEC - PLANTÃO)",
"PCPE - DINTER 2 - Plantão da 23ª DESEC - Salgueiro (PCPE - 23ª DESEC - PLANTÃO)",
"PCPE - DINTER 2 - 19ª Delegacia Seccional de Policia - Arcoverde (PCPE - DINTER 2 - 19ª DESEC)",
"PCPE - DINTER 2 - 20ª Delegacia Seccional de Policia - Afogados da Ingazeira (PCPE - DINTER 2 - 20ª DESEC)",
"PCPE - DINTER 2 - 21ª Delegacia Seccional de Policia - Serra Talhada (PCPE - DINTER 2 - 21ª DESEC)",
"PCPE - DINTER 2 - 22ª Delegacia Seccional de Policia - Floresta (PCPE - DINTER 2 - 22ª DESEC)",
"PCPE - DINTER 2 - 23ª Delegacia de Policia de Homicídios  - Arcoverde (PCPE - DINTER 2 - 23ª DPH)",
"PCPE - DINTER 2 - 23ª Delegacia Seccional de Policia - Salgueiro (PCPE - DINTER 2 - 23ª DESEC)",
"PCPE - DINTER 2 - 24ª Delegacia de Policia de Homicídios  - Araripina (PCPE - DINTER 2 - 24ª DPH)",
"PCPE - DINTER 2 - 24ª Delegacia Seccional de Policia - Araripina (PCPE - DINTER 2 - 24ª DESEC)",
"PCPE - DINTER 2 - 25ª Delegacia de Policia de Homicídios  - Petrolina (PCPE - DINTER 2 - 25ª DPH)",
"PCPE - DINTER 2 - 25ª Delegacia Seccional de Policia - Cabrobró (PCPE - DINTER 2 - 25ª DESEC)",
"PCPE - DINTER 2 - 26ª Delegacia Seccional de Policia - Petrolina (PCPE - DINTER 2 - 26ª DESEC)",
"PCPE - DINTER1 - Divisão de Adm., Planejamento e Logística do Interior 1 (PCPE - DINTER1 - DIVAPLIN 1)",
"PCPE - DINTER1 - Divisão de Planejamento Operacional do Interior (PCPE - DINTER1 - DIVIPLOI 1)",
"PCPE - DINTER1 - Setor de Administração, Planejamento e Logística (PCPE - DINTER1 - SAPLOG/DHA)",
"PCPE - DINTER1 - Setor de Remessa e Controle da DHA (PCPE - DINTER1 - SERCON/DHA)",
"PCPE - DINTER1 - 14ª DELEGACIA SECCIONAL CARUARU - RASTRO (PCPE -DINTER1-CARUARU-RASTRO)",
"PCPE - DINTER1 - 16ª Delegacia de Polícia de Homicídios - Goiana (PCPE - DINTER1 - 16ª DPH)",
"PCPE - DINTER1 - 17ª Delegacia de Polícia de Homicídios - Vitória de Santo Antão (PCPE - DINTER1 - 17ª DPH)",
"PCPE - DINTER1 - 18ª Delegacia de Polícia de Homicídios - Palmares (PCPE - DINTER1 - 18ª DPH)",
"PCPE - DINTER1 - 19ª Delegacia de Polícia de Homicídios - Caruaru (PCPE - DINTER1 - 19ª DPH)",
"PCPE - DINTER1 - 20ª Delegacia de Polícia de Homicídios - Caruaru (PCPE - DINTER1 - 20ª DPH)",
"PCPE - DINTER1 - 21ª Delegacia de Polícia de Homicídios - Sta. Cruz do Capibaribe (PCPE - DINTER1 - 21ª DPH)",
"PCPE - DINTER1 - 22ª Delegacia de Polícia de Homicídios - Garanhuns (PCPE - DINTER1 - 22ª DPH)",
"PCPE - DINTER2 - NI26ª DESEC - NUCLEO CELLEBRITE-SERTAO (PCPE -NI26ªD -CELLEBRITE-SRT)",
"PCPE - DINTER2 - 24ª DESEC DE PLANTAO - ARARIPINA (PCPE - 24ª DESEC - PLANTAO)",
"PCPE - DIRESP - Delegacia de Polícia da 36ª Circunscrição - Fernando de Noronha (PCPE - DIRESP - DP 36ª CIRC)",
"PCPE - DIRESP - Delegacia de Polícia de Crimes contra a Adm Pública e Serviços Públicos (PCPE - DIRESP - DECASP)",
"PCPE - DIRESP - Delegacia de Polícia de Crimes contra a Ordem Tributária (PCPE - DIRESP - DECCOT)",
"PCPE - DIRESP - Delegacia de Polícia de Crimes contra a Propriedade Imaterial (PCPE - DIRESP - DEPRIM)",
"PCPE - DIRESP - Delegacia de Polícia de Crimes contra o Consumidor (PCPE - DIRESP - DECON)",
"PCPE - DIRESP - Delegacia de Polícia do Meio Ambiente (PCPE - DIRESP - DEPOMA)",
"PCPE - DIRESP - Delegacia de Polícia Interestadual e Capturas (PCPE - DIRESP - POLINTER)",
"PCPE - DIRESP - Delegacia Interativa (PCPE - DIRESP - DELINTER)",
"PCPE - DIRESP - Departamento de Repressão ao Narcotráfico (PCPE - DIRESP - DENARC)",
"PCPE - DIRESP - Departamento de Repressão aos Crimes Patrimoniais (PCPE - DIRESP - DEPATRI)",
"PCPE - DIRESP - Divisão de Administração, Planejamento e Logística Especializada (PCPE - DIRESP - DIVAPLE)",
"PCPE - DIRESP - Divisão de Homicídios Metropolitana Norte (PCPE - DIRESP - DHMN)",
"PCPE - DIRESP - Divisão de Homicídios Metropolitana Sul (PCPE - DIRESP - DHMS)",
"PCPE - DIRESP - Divisão de Planejamento Operacional Especializado (PCPE - DIRESP - DIVPLOE)",
"PCPE - DIRESP - FORCA TAREFA BANCO AGRESTE (PCPE - DIRESP-FTBANCO-AGRESTE)",
"PCPE - DIRESP - FORCA TAREFA BANCO CAPITAL (PCPE - DIRESP-FTBANCO-CAPITAL)",
"PCPE - DIRESP - FORÇA TAREFA DE SEGURANÇA PÚBLICA DE PERNAMBUCO (PCPE - DIRESP - FTSP)",
"PCPE - DIRESP - FORCATAREFASERTAO1 (PCPE - DIRESP-FTBANCOSERTAO1)",
"PCPE - DIRESP - FORCATAREFASERTAO2 (PCPE - DIRESP-FTBANCOSERTAO2)",
"PCPE - DIRESP - Gerência de Controle Operacional Especializada da Polícia Civil (PCPE - DIRESP - GCOE)",
"PCPE - DIRESP - Núcleo de Inteligência da DECASP (PCPE - DIRESP - NIDECASP)",
"PCPE - DIRESP - Núcleo de Inteligência da DECCOT (PCPE - DIRESP - NIDECCOT)",
"PCPE - DIRESP - Núcleo de Inteligência da GCOE (PCPE - DIRESP - NIGCOE)",
"PCPE - DIRESP - Núcleo de Inteligência do GOE (PCPE - DIRESP - NIGOE)",
"PCPE - DIRESP - Plantão da Delegacia de Polícia de Homicídios de Paulista - FSN (PCPE - DIRESP - PLAN DPH PAUL)",
"PCPE - DIRESP - Setor de Administração, Planejamento e Logística da DHMN (PCPE - DIRESP - SAPLOG/DHMN)",
"PCPE - DIRESP - Setor de Administração, Planejamento e Logística da DHMS (PCPE - DIRESP - SAPLOG/DHMS)",
"PCPE - DIRESP - Setor de Remessa e Controle da DHMN (PCPE - DIRESP - SERCON/DHMN)",
"PCPE - DIRESP - Setor de Remessa e Controle da DHMS (PCPE - DIRESP - SERCON/DHMS)",
"PCPE - DIRESP - 10ª Delegacia de Polícia de Homicídios - São Lourenço da Mata (PCPE - DIRESP - 10ª DPH)",
"PCPE - DIRESP - 10ª Delegacia de Polícia de Repressão ao Narcotráfico - Serra de Talhada (PCPE - DIRESP - 10ª DPRN)",
"PCPE - DIRESP - 11ª Delegacia de Polícia de Homicídios - Jaboatão dos Guararapes (PCPE - DIRESP - 11ª DPH)",
"PCPE - DIRESP - 11ª Delegacia de Polícia de Repressão ao Narcotráfico - Ouricuri (PCPE - DIRESP - 11ª DPRN)",
"PCPE - DIRESP - 12ª Delegacia de Polícia de Homicídios - Jaboatão dos Guararapes (PCPE - DIRESP - 12ª DPH)",
"PCPE - DIRESP - 12ª Delegacia de Polícia de Repressão ao Narcotráfico - Petrolina (PCPE - DIRESP - 12ª DPRN)",
"PCPE - DIRESP - 13ª Delegacia de Polícia de Homicídios - Jaboatão dos Guararapes/Moreno (PCPE - DIRESP - 13ª DPH)",
"PCPE - DIRESP - 14ª Delegacia de Polícia de Homicídios - Cabo de Stº Agostinho (PCPE - DIRESP - 14ª DPH)",
"PCPE - DIRESP - 15ª Delegacia de Polícia de Homicídios - Ipojuca (PCPE - DIRESP - 15ª DPH)",
"PCPE - DIRESP - 4ª Delegacia de Polícia de Repressão ao Narcotráfico - Cabo de Stº Agostinho (PCPE - DIRESP - 4ª DPRN)",
"PCPE - DIRESP - 5ª Delegacia de Polícia de Repressão ao Narcotráfico - Goiana (PCPE - DIRESP - 5ª DPRN)",
"PCPE - DIRESP - 6ª Delegacia de Polícia de Homicídios - Paulista (PCPE - DIRESP - 6ª DPH)",
"PCPE - DIRESP - 6ª Delegacia de Polícia de Repressão ao Narcotráfico - Vitória de Sto Antão (PCPE - DIRESP - 6ª DPRN)",
"PCPE - DIRESP - 7ª Delegacia de Polícia de Homicídios - Paulista (PCPE - DIRESP - 7ª DPH)",
"PCPE - DIRESP - 7ª Delegacia de Polícia de Repressão ao Narcotráfico - Caruaru (PCPE - DIRESP - 7ª DPRN)",
"PCPE - DIRESP - 8ª Delegacia de Polícia de Homicídios - Paulista (PCPE - DIRESP - 8ª DPH)",
"PCPE - DIRESP - 8ª Delegacia de Polícia de Repressão ao Narcotráfico - Garanhuns (PCPE - DIRESP - 8ª DPRN)",
"PCPE - DIRESP - 9ª Delegacia de Polícia de Homicídios - Olinda (PCPE - DIRESP - 9ª DPH)",
"PCPE - DIRESP - 9ª Delegacia de Polícia de Repressão ao Narcotráfico - ArcoVerde (PCPE - DIRESP - 9ª DPRN)",
"PCPE - Diretoria de Administração geral da Policia Civil (PCPE - DIAG)",
"PCPE - Diretoria de Inteligencia da Policia Civil (PCPE - DINTEL)",
"PCPE - Diretoria de Recursos Humanos da Policia Civil (PCPE - DIRH)",
"PCPE - Diretoria de Tecnologia da Informação da Policia Civil (PCPE - DTI)",
"PCPE - Diretoria Integrada do interior 1 da Polícia Civil (PCPE - DINTER 1)",
"PCPE - Diretoria Integrada do Interior 2 da Polícia Civil (PCPE - DINTER 2)",
"PCPE - Diretoria Integrada Especializada da Polícia Civil (PCPE - DIRESP)",
"PCPE - Diretoria Integrada Metropolitana da Polícia Civil (PCPE - DIM)",
"PCPE - DIRH - Comissão de Estágio Probatório (PCPE - DIRH - CEP)",
"PCPE - DIRH - Divisão Administrativa da UNICADE (PCPE - DIRH - UNICADE - DIVAD)",
"PCPE - DIRH - Divisão de  Assistência  Psicológica (PCPE - DIRH - DIVASP)",
"PCPE - DIRH - Divisão de Apresentação de Servidores a Justiça (PCPE - DIRH - DIVJUST)",
"PCPE - DIRH - Divisão de Assistencia Social (PCPE - DIRH - DIVASS)",
"PCPE - DIRH - Divisão de Atendimento ao Servidor (PCPE - DIRH - DIVSERV)",
"PCPE - DIRH - Divisão de Cadastro de Pessoal (PCPE - DIRH - DIVCAP)",
"PCPE - DIRH - Divisão de Controle de Cargos e Funções Gratificadas (PCPE - DIRH - DIVFUNG)",
"PCPE - DIRH - Divisão de Desempenho e Avaliação de Pessoal (PCPE - DIRH - DIVDAP)",
"PCPE - DIRH - Divisão de Desenvolvimento Institucional (PCPE - DIRH - DIVDI)",
"PCPE - DIRH - Divisão de Elaboração de Portarias (PCPE - DIRH - DIVPORT)",
"PCPE - DIRH - Divisão de Folha de Pagamento (PCPE - DIRH - DIVFOP)",
"PCPE - DIRH - Divisão de Protocolo (PCPE - DIRH - DIVPROT)",
"PCPE - DIRH - Divisão de Saude - Governador Eduardo Henrique Accioly Campos (PCPE - DIRH - DIVSA)",
"PCPE - DIRH - Divisão de Segurança  e Logistica (PCPE - DIRH - DIVSEL)",
"PCPE - DIRH - MUSEU (PCPE - DIRH - MUSEU)",
"PCPE - DIRH - UNESAV - PROJETOS E PESQUISAS (PCPE - DIRH - UNESAV - PROPESQ)",
"PCPE - DIRH - UNICADE - Comissão Administrativa de Avaliação do Enquadramenteo e Acompanhamento do PCCV (PCPE - DIRH - UNICADE - CAPCCV)",
"PCPE - DIRH - UNICADE - Grupo Ocupacional de Gestão Pública (PCPE - DIRH - UNICADE - GOGP)",
"PCPE - DIRH - Unidade de Administração de Pessoal (PCPE - DIRH - UNIAP)",
"PCPE - DIRH - Unidade de Capacitação e Desenvolvimento (PCPE - DIRH - UNICADE)",
"PCPE - DIRH - Unidade de Estudos e Gerenciamentos de Saúde e Valorização Profissional (PCPE - DIRH - UNESAV)",
"PCPE - DIRH - Unidade de Movimentação de Pessoal (PCPE - DIRH - UNIMOPE)",
"PCPE - DITER 1 - Delegacia de Policia da 70ª Circunscrição - Palmares (PCPE - DINTER 1 - DP 70ª CIRC)",
"PCPE - Divisão Administrativa da DIRH (PCPE - DIRH - DIVAD)",
"PCPE - Divisão de  Orçamento - DIAG (PCPE - DIAG - DIVOR)",
"PCPE - Divisão de Administração e Controle (PCPE - DIVAC)",
"PCPE - Divisão de Analise e Estatística da DIRH (PCPE - DIRH - DIVAE)",
"PCPE - Divisão de Controladoria e Auditoria em Contratos (PCPE - DIVCAC)",
"PCPE - Divisão de Fiscalização de Autos Processuais da RMR (PCPE - DIFARME)",
"PCPE - Divisão de Homicídios Agreste (PCPE - DINTER 1 - DHA)",
"PCPE - Divisão de Investigação e Apuração - Tribunal de Justiça de Pernambuco (PCPE - APMC TJPE - DIA)",
"PCPE - Divisão de Redes de Computadores (PCPE - DTI - UNISUT - DIVREC)",
"PCPE - DPCA - Assessoria da PCPE (PCPE - DPCA - ASSPCPE)",
"PCPE - DPCA - Assessoria do DPCA (PCPE - DPCA - ASSDPCA)",
"PCPE - DPCA - DECCA PLANTÃO - Plantão da Delegacia da Criança e Adolescente (PCPE - DPCA - DECCA PLANTAO)",
"PCPE - DPCA - Delegacia de Policia de Crimes Contra Criança e Adolescente (PCPE - DPCA - DECCA)",
"PCPE - DPCA - Divisão de Atendimento Técnico (PCPE - DPCA - DIVAT)",
"PCPE - DPCA - Divisão de Desaparecidos (PCPE - DPCA - DIVDES)",
"PCPE - DPCA - Divisão de Estatística (PCPE - DPCA - DIVEST)",
"PCPE - DPCA - PLANTÃO DA DEPAI - 1ª EQUIPE (PCPE - DPCA - DEPAI - EQ 1)",
"PCPE - DPCA - PLANTÃO DA DEPAI - 2ª EQUIPE (PCPE - DPCA - DEPAI - EQ 2)",
"PCPE - DPCA - PLANTÃO DA DEPAI - 3ª EQUIPE (PCPE - DPCA - DEPAI - EQ 3)",
"PCPE - DPCA - PLANTÃO DA DEPAI - 4ª EQUIPE (PCPE - DPCA - DEPAI - EQ 4)",
"PCPE - DPCA - Setor de Denúncias da Delegacia de Policia de Crimes Contra Criança e Adolescente (PCPE - DPCA - DENUNCIAS)",
"PCPE - DPCA - Unidade de Prevenção aos Crimes Contra Criança e Adolescente (PCPE - DPCA - UNIPRECCA)",
"PCPE - DPCA - Unidade de Prevenção e Repressão aos Atos Infracionais (PCPE - DPCA - UNIPRAI)",
"PCPE - DPCA - 1ª Delegacia de Policia de Crimes Contra Criança e Adolescente e Atos Infracionais - Paulista (PCPE - DPCA - 1ª DPCCAI)",
"PCPE - DPCA - 2ª Delegacia de Policia de Crimes Contra Crianças e Adolescente e Atos Infracionais - Jaboatão dos Guararapes (PCPE - DPCA - 2ª DPCCAI)",
"PCPE - DPMUL - Assessoria da PCPE (PCPE - DPMUL - ASSPCPE)",
"PCPE - DPMUL - Assessoria do DPMUL (PCPE - DPMUL - ASSDPMUL)",
"PCPE - DPMUL - Núcleo de Prevenção aos Crimes Contra a Mulher (PCPE - DPMUL - NUPREM)",
"PCPE - DPMUL - 1ª Delegacia Especializada de Atendimento à Mulher - Stº Amaro (PCPE - DPMUL - 1ª DEAM)",
"PCPE - DPMUL - 1ª Delegacia Especializada de Atendimento à Mulher - Stº Amaro - Plantão - 1ª Equipe (PCPE - DPMUL - 1ª DEAM - EQ 1)",
"PCPE - DPMUL - 1ª Delegacia Especializada de Atendimento à Mulher - Stº Amaro - Plantão - 2ª Equipe (PCPE - DPMUL - 1ª DEAM - EQ 2)",
"PCPE - DPMUL - 1ª Delegacia Especializada de Atendimento à Mulher - Stº Amaro - Plantão - 3ª Equipe (PCPE - DPMUL - 1ª DEAM - EQ 3)",
"PCPE - DPMUL - 1ª Delegacia Especializada de Atendimento à Mulher - Stº Amaro - Plantão - 4ª Equipe (PCPE - DPMUL - 1ª DEAM - EQ 4)",
"PCPE - DPMUL - 10ª Delegacia Especializada de Atendimento à Mulher - Vitoria de Stº Antão (PCPE - DPMUL - 10ª DEAM)",
"PCPE - DPMUL - 11ª Delegacia Especializada de Atendimento à Mulher - Salgueiro (PCPE - DPMUL - 11ª DEAM)",
"PCPE - DPMUL - 12ª Delegacia Especializada de Atendimento à Mulher - Ouricuri (PCPE - DPMUL - 12ª DEAM)",
"PCPE - DPMUL - 13ª Delegacia Especializada de Atendimento à Mulher - Afogados da Ingazeira (PCPE - DPMUL - 13ª DEAM)",
"PCPE - DPMUL - 14ª Delegacia Especializada de Atendimento à Mulher - Cabo de Stº Agostinho (PCPE - DPMUL - 14ª DEAM)",
"PCPE - DPMUL - 15ª Delegacia Especializada de Atendimento à Mulher - Olinda (PCPE - DPMUL - 15ª DEAM)",
"PCPE - DPMUL - 15ª Delegacia Especializada de Atendimento à Mulher - Olinda - Plantão - 1ª Equipe (PCPE - DPMUL - 15ª DEAM - EQ1)",
"PCPE - DPMUL - 15ª Delegacia Especializada de Atendimento à Mulher - Olinda - Plantão - 2ª Equipe (PCPE - DPMUL - 15ª DEAM - EQ2)",
"PCPE - DPMUL - 15ª Delegacia Especializada de Atendimento à Mulher - Olinda - Plantão - 3ª Equipe (PCPE - DPMUL - 15ª DEAM - EQ3)",
"PCPE - DPMUL - 15ª Delegacia Especializada de Atendimento à Mulher - Olinda - Plantão - 4ª Equipe (PCPE - DPMUL - 15ª DEAM - EQ4)",
"PCPE - DPMUL - 16ª Delegacia Especializada de Atendimento à Mulher - Palmares (PCPE - DPMUL - 16ª DEAM)",
"PCPE - DPMUL - 17ª Delegacia Especializada de Atendimento à Mulher - Arcoverde (PCPE - DPMUL - 17ª DEAM)",
"PCPE - DPMUL - 2ª Delegacia Especializada de Atendimento à Mulher - Prazeres (PCPE - DPMUL - 2ª DEAM)",
"PCPE - DPMUL - 2ª Delegacia Especializada de Atendimento à Mulher - Prazeres - Plantão - 1ª Equipe (PCPE - DPMUL - 2ª DEAM - EQ 1)",
"PCPE - DPMUL - 2ª Delegacia Especializada de Atendimento à Mulher - Prazeres - Plantão - 2ª Equipe (PCPE - DPMUL - 2ª DEAM - EQ 2)",
"PCPE - DPMUL - 2ª Delegacia Especializada de Atendimento à Mulher - Prazeres - Plantão - 3ª Equipe (PCPE - DPMUL - 2ª DEAM - EQ 3)",
"PCPE - DPMUL - 2ª Delegacia Especializada de Atendimento à Mulher - Prazeres - Plantão - 4ª Equipe (PCPE - DPMUL - 2ª DEAM - EQ 4)",
"PCPE - DPMUL - 3ª Delegacia Especializada de Atendimento à Mulher - Petrolina (PCPE - DPMUL - 3ª DEAM)",
"PCPE - DPMUL - 4ª Delegacia Especializada de Atendimento à Mulher - Caruaru (PCPE - DPMUL - 4ª DEAM)",
"PCPE - DPMUL - 5ª Delegacia Especializada de Atendimento à Mulher - Paulista (PCPE - DPMUL - 5ª DEAM)",
"PCPE - DPMUL - 5ª Delegacia Especializada de Atendimento à Mulher - Paulista - Plantão - 1ª Equipe (PCPE - DPMUL - 5ª DEAM - EQ 1)",
"PCPE - DPMUL - 5ª Delegacia Especializada de Atendimento à Mulher - Paulista - Plantão - 2ª Equipe (PCPE - DPMUL - 5ª DEAM - EQ 2)",
"PCPE - DPMUL - 5ª Delegacia Especializada de Atendimento à Mulher - Paulista - Plantão - 3ª Equipe (PCPE - DPMUL - 5ª DEAM - EQ 3)",
"PCPE - DPMUL - 5ª Delegacia Especializada de Atendimento à Mulher - Paulista - Plantão - 4ª Equipe (PCPE - DPMUL - 5ª DEAM - EQ 4)",
"PCPE - DPMUL - 5ª Delegacia Especializada de Atendimento à Mulher - Plantão (PCPE - DPMUL - 5ª DEAM PLANTAO)",
"PCPE - DPMUL - 6ª Delegacia Especializada de Atendimento à Mulher - Ipojuca (PCPE - DPMUL - 6ª DEAM)",
"PCPE - DPMUL - 7ª Delegacia Especializada de Atendimento à Mulher - Surubim (PCPE - DPMUL - 7ª DEAM)",
"PCPE - DPMUL - 8ª Delegacia Especializada de Atendimento à Mulher - Goiana (PCPE - DPMUL - 8ª DEAM)",
"PCPE - DPMUL - 9ª Delegacia Especializada de Atendimento à Mulher - Garanhuns (PCPE - DPMUL - 9ª DEAM)",
"PCPE - DRONES DO CORE (PCPE - CORE - DRONES)",
"PCPE - DTI - Núcleo da Diretoria de Tecnologia da Informação na Dinter 1 (PCPE - DTI - DINTER 1)",
"PCPE - DTI - Recursos Administrativos (PCPE - DTI -  UNISUT - RAM)",
"PCPE - DTI - UNISA - Setor de Suporte aos Sistemas em Maker (PCPE - DTI - UNISA - MAKER)",
"PCPE - Gabinete do Chefe de Policia Civil (PCPE - GABPCPE)",
"PCPE - Gerência de Controle Operacional Interior 2 da Polícia Civil (PCPE - DINTER 2 - GCOI 2)",
"PCPE - Grupo de Operações Especiais (PCPE - DIRESP - GOE)",
"PCPE - IITB - LABORATORIO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL (PCPE - IITB - LABORATORIO)",
"PCPE - IITB  NECROPAPILOSCOPIA - CARUARU (PCPE - IITB - NECRO - CARUARU)",
"PCPE - IITB - Núcleo de Identificação Forense - Afogados da Ingazeira (PCPE - IITB - NIF AFOGADOS)",
"PCPE - IITB - Núcleo de Identificação Forense - Departamento de Homicídios e de Proteção à Pessoa - DHPP (PCPE - IITB - NIF DHPP)",
"PCPE - IITB - Núcleo de Identificação Forense - Petrolina (PCPE - IITB - NIF PETROLINA)",
"PCPE - IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL (PCPE - IITB - RASTRO)",
"PCPE - IITB - Setor de Confrontos e Laudos de Local de Crime (PCPE - IITB - SECOL)",
"PCPE - IITB NECROPAPILOSCOPIA - PETROLINA (PCPE - IITB - NECRO- PETROLINA)",
"PCPE - IITB NECROPAPILOSCOPIA - RECIFE (PCPE - IITB - NECRO - RECIFE)",
"PCPE - LAUDOS DAS AUDIÊNCIAS DE CUSTÓDIA (PCPE - LAUDOS - AUDIENCIAS)",
"PCPE - NI 26ª DESEC - Arcoverde (PCPE - NI 26ª D - ARCOVERDE)",
"PCPE - PERICIAS CONCLUIDAS (PCPE - PERICIAS CONCLUIDAS)",
"PCPE - Plantão da DTI (PCPE - DTI - PLANTÃO)",
"PCPE - Plantão da 17ª DESEC - SANTA CRUZ DO CAPIBARIBE (PCPE - 17ª DESEC - PLANTÃO)",
"PCPE - Plantão da 18ª DESEC - Garanhuns (PCPE - 18ª DESEC - PLANTÃO)",
"PCPE - Protoloco do Instituto de Identificação Tavares Buril (PCPE - IITB - PROTOCOLO)",
"PCPE - Secretaria do GABPC (PCPE - SEGAB - PROTOCOLO)",
"PCPE - Setor de Análise de Processos de Pessoal da Unidade de Apoio Jurídico (PCPE - UNAJUR - APP)",
"PCPE - Setor de Arquivos da Diretoria da DTI (PCPE - DTI - ARQUIVO DIRETORIA)",
"PCPE - Setor de Identidade Funcional (PCPE - DIRH - IDENT FUNC)",
"PCPE - Setor de Licitações, Contratos e Convênios da Unidade de Apoio Jurídico (PCPE - UNAJUR - LCC)",
"PCPE - SUBCHEFIA - GABINETE DE RECUPERAÇÃO DE ATIVOS (PCPE  - SUBPC - GRA)",
"PCPE - Subchefia da Polícia Civil (PCPE - SUBCP)",
"PCPE - SUINT - Assessor Técnico Especial (PCPE - SUINT - ATEC)",
"PCPE - SUINT - Departamento de Inteligência e Investigação (PCPE - SUINT - DII)",
"PCPE - SUINT - Gerência Administrativa Cartorial (PCPE - SUINT - GAC)",
"PCPE - SUINT - Gerência de Inteligência (PCPE - SUINT - GINT)",
"PCPE - SUINT - Gerência de Investigação (PCPE - SUINT - GINV)",
"PCPE - SUINT - Gerência de Segurança Patrimonial (PCPE - SUINT - GSP)",
"PCPE - SUINT - Superintendente Chefe (PCPE - SUINT - SUPCH)",
"PCPE - Superintendência de Inteligência Legislativa - SUINT (PCPE - SUINT)",
"PCPE - Unidade de  Apoio Técnico - DPCA (PCPE - DPCA - UNIAT)",
"PCPE - Unidade de  Contratos e  Convênios - Setor Administrativo (PCPE - DIAG - UNICCON - ADM)",
"PCPE - Unidade de  Contratos e  Convênios - Setor de Contratos Administrativos (PCPE - DIAG - UNICCON - CONADM)",
"PCPE - Unidade de  Contratos e  Convenios - Setor de Contratos de Locacao de Imoveis (PCPE - DIAG - UNICCON - IMOV)",
"PCPE - Unidade de  Contratos e  Convênios - Setor de Convênios (PCPE - DIAG - UNICCON - CONV)",
"PCPE - Unidade de  Fiscalização de Atividades Licenciadas e Ordem Pública (PCPE - CORE - UNIFALOP)",
"PCPE - Unidade de Apoio Jurídico (PCPE - UNAJUR)",
"PCPE - Unidade de Controle Interno da SUBCP (PCPE - UCI/SUBCP)",
"PCPE - Unidade de Estatística Criminal (PCPE - UNESTAC)",
"PCPE - Unidade de Infraestrutura e Atendimento (PCPE - DTI - UNIATE)",
"PCPE - Unidade de Planejamento e Coordenação de Eventos (PCPE - UNICEV)",
"PCPE - Unidade de Sistema e Aplicativo (PCPE - DTI - UNISA)",
"PCPE - Unidade de Suporte Técnico (PCPE - DTI - UNISUT)",
"PCPE- IITB - GAB - DIVPROJ - DIVISÃO DE PROJETOS (PCPE - IITB - GAB - DIVPROJ)",
"Plantão da DEPAI - DPCA (PCPE - DPCA - DEPAI - PLANTAO)",
"Protocolo DTI (PCPE - DTI - UNIATE - PROT)",
"Representação Facial Humana da DIVCRIM - IITB (PCPE - IITB - DIVCRIM.RFH)",
"Setor de Cadastro de Usuários da DTI (PCPE - DTI - UNISUT - CADASTRO)",
"Setor de Controle de PJES (PCPE - SEGAB - PJES)",
"SETOR DE DIÁRIAS DO GABINETE DO CHEFE DE POLÍCIA CIVIL (PCPE - GAB - DIARIAS)",
"Setor de Documentos (diretoria) (PCPE - DTI - SD)",
"Setor de Equipamentos Locados da DTI (PCPE - DTI - UNIATE - EQUIPLOC)",
"Setor de Exigência (PCPE - IITB - UTICIV-EXIGÊNCIA)",
"Setor de Hardware da UNIATE (PCPE - DTI - UNIATE - HARDWARE)",
"Setor de Help Desk da DTI (PCPE - DTI - UNISUT - HELPDESK)",
"Setor de Liberações - UTICIV - IITB (PCPE - IITB - UTICIV - LIBERA)",
"Setor de Ofícios do IITB (PCPE - IITB - UTICIV - OFICIOS)",
"Setor de Ouvidoria do SEGAB (PCPE - SEGAB - OUVIDORIA)",
"Setor de Perícia e Pesquisa de Identificação Criminal (PCPE - IITB - PESQCRIM)",
"Setor de Pesquisas Papiloscópicas (PCPE - IITB - UTICIV- PESQPAPI)",
"Setor de Telemática da DTI (PCPE - DTI - TELEM)",
"Setor Financeiro da DTI (PCPE - DTI - FINANC)",
"Supervisão do Expresso Cidadão 02 - Boa Vista (PCPE - IITB - UTICIV - S.EC2)",
"Supervisão do Expresso Cidadão 03 - Olinda (PCPE - IITB - UTICIV - S.EC3)",
"Supervisão do Expresso Cidadão 04 - Petrolina (PCPE - IITB - UTICIV - S.EC4)",
"Supervisão do Expresso Cidadão 05 - Caruaru (PCPE - IITB - UTICIV - S.EC5)",
"Supervisão do Expresso Cidadão 07 - Garanhuns (PCPE - IITB - UTICIV - S.EC7)",
"Supervisão do Expresso Cidadão 09 - Pina (PCPE - IITB - UTICIV - S.EC9)",
"Supervisão do Expresso Cidadão 11 - Salgueiro (PCPE - IITB - UTICIV - S.EC11)",
"Supervisão do Expresso Cidadão 12 - Vitória de Santo Antão (PCPE - IITB - UTICIV - S.EC12)",
"Unidade para Policiais cedidos a outros órgãos (PCPE - POLICIAIS - CEDIDOS)",
"Unidade Técnica Administrativa do Instituto de Identificação Tavares Buril (PCPE - IITB - UTADM)",
"Unidade Técnica de Identificação Civil (PCPE - IITB - UTICIV)",
"Unidade Técnica de Identificação Criminal (PCPE - IITB - UTICR)",
"1ª Delegacia de Combate à Corrupção - DRACCO (PCPE - DRACCO - 1ª DECCOR)",
"1ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 1)",
"10ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 10)",
"11ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 11)",
"12ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 12)",
"13ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 13)",
"14ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 14)",
"15ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 15)",
"16ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 16)",
"17ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 17)",
"2ª Delegacia de Combate à Corrupção - DRACCO (PCPE - DRACCO - 2ª DECCOR)",
"2ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 2)",
"3ª Delegacia de Combate à Corrupção - DRACCO (PCPE - DRACCO - 3ª DECCOR)",
"3ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 3)",
"4ª Delegacia de Combate à Corrupção - DRACCO (PCPE - DRACCO - 4ª DECCOR)",
"4ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 4)",
"5ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 5)",
"6ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 6)",
"7ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 7)",
"8ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 8)",
"9ª Equipe de Plantão da CEPLANC (PCPE - DIM - CEPLANC - EQ 9)"
];

export{
    options
}